---
title: "R Notebook"
output: html_notebook
---
 

```{r}
load("../output/ms_test_mat.RData")
load("../output/movie_test_mat.RData")
```

# sim rank
```{r}
load("../output/prediction/ms/pred_sim_ms.RData")
sim_ms_rank_score <- rank_score(sim.MS.pred, ms_test_mat)
sim_ms_mae <- MAE(sim.MS.pred, ms_test_mat)
```

# person
```{r}
load("../output/prediction/ms/pred_spearman_ms.RData")
sp_ms_rank_score <- rank_score(sp.MS.pred, ms_test_mat)
sp_ms_mae <- MAE(sp.MS.pred, ms_test_mat)
```

```{r}
load("../output/prediction/movie/pred_spearman_movie.RData")
sp_movie_rank_score <- rank_score(sp.movie.pred, movie_test_mat)
sp_movie_mae <- MAE(sp.movie.pred, movie_test_mat)
```

```{r}
# rank score 
rank_score <-function(predict, true, d=0, alpha=10){
  
  n <- nrow(true)
  r <- rep(0,n)
  r_max <- rep(0,n)
  
  for(a in 1:n){
    
    predict[a] <- sort(predict[a],decreasing = T)
    true[a,] <- sort(true[a,],decreasing = T)
    
    for(j in 1:ncol(true)){
      
      r[a] <- r[a]+max(predict[a,]-d,0)/2^((j-1)/(alpha-1))
      r_max[a] <- r_max[a]+sum(max(true[a,]-d,0)/2^((j-1)/(alpha-1)))
      
    }
  }
  
  score <- 100*sum(r)/sum(r_max)
  return(score)
}

# MAE
MAE <- function(pred, true){
  mae <- mean(abs(pred - true), na.rm = T)
  return(mae)
}
```