---
title: "Test_vw"
author: "Yuexuan Huang UNI yh2966"
date: "4/11/2018"
output: html_document
---

```{r}
## Variance Weighting
find_var <- function(mat=movie_train){
  vari <- apply(mat, 2, var, na.rm=TRUE)
  var_max <- max(vari, na.rm = TRUE)
  var_min <- min(vari, na.rm = TRUE)
  vi <- (vari - var_min)/var_max
  return(vi)
}

variance_weight_assign <- function(i, j, vi, mat=movie_train){
  zai <- scale(mat[i, ])
  zui <- scale(mat[j, ])
  index <- intersect(which(!is.na(zai)), which(!is.na(zui)))
  wau <- sum(vi[index]*zai[index]*zui[index])/sum(vi[index])
  return(wau)
}

variance_weight_matrix <- function(mat_dim_1, mat = movie_train){
  mat_weight = matrix(1, nrow=mat_dim_1, ncol=mat_dim_1)
  vi <- find_var(mat = mat)
  for (i in 1:(mat_dim_1-1)){
    print(i)
    print(Sys.time())
    for (j in (i+1):mat_dim_1){
      wau <- variance_weight_assign(i, j, vi, mat = movie_train)
      mat_weight[i, j] <- wau
      mat_weight[j, i] <- wau
    }
  }
  return(mat_weight)
}
```

```{r}
## For Dataset Movie
Transformer <- function(data.set){
  columns.data <- sort(unique(data.set$Movie))
  rows.data <- sort(unique(data.set$User))
  Table_ <- matrix(NA,nrow = length(rows.data), ncol = length(columns.data))
  for(i in 1:length(columns.data)){
    col.name <- columns.data[i]
    index <- which(data.set$Movie == col.name)
    scores <- data.set[index,4] 
    users <- data.set[index,3] 
    index2 <- which(rows.data %in% users)
    Table_[index2,i] = scores
    Table_[!index2,i] = NA
  }
  colnames(Table_) <- columns.data
  rownames(Table_) <- rows.data
  return(Table_)
}

## For Dataset MS
Transformer2 <- function(data){
  user_num <- which(data$V1 == 'C')
  user_id <- data$V2[user_num]
  page_id <- unique(data$V2[which(data$V1 == 'V')])
  Table_2 <- matrix(0, nrow=length(user_id), ncol=length(page_id))
  rownames(Table_2) <- as.character(user_id)
  colnames(Table_2) <- as.character(page_id)
  for (i in 1:length(user_num)){
    start_num <- user_num[i]
    if (i != length(user_num)){
      end_num <- user_num[i+1]
    }
    else {
      end_num <- nrow(data)+1
    }
    
    user_id_mat <- as.character(user_id[i])
    
    for (j in (start_num+1):(end_num-1)){
      page_id_mat <- as.character(data$V2[j])
      Table_2[user_id_mat, page_id_mat] <- 1
    }
  }
  return(Table_2)
}
```

```{r}
movie_train <- read.csv("~/Documents/GitHub/Spring2018-Project4-grp-8/data/eachmovie_sample/data_train.csv")
movie_test <- read.csv("~/Documents/GitHub/Spring2018-Project4-grp-8/data/eachmovie_sample/data_test.csv")
MS_train <- read.csv("~/Documents/GitHub/Spring2018-Project4-grp-8/data/MS_sample/data_train.csv")
MS_test <- read.csv("~/Documents/GitHub/Spring2018-Project4-grp-8/data/MS_sample/data_test.csv")
```

```{r}
movie_train <- Transformer(movie_train)
movie_test <- Transformer(movie_test)
MS_train <- Transformer2(MS_train)
MS_test <- Transformer2(MS_test)
```

```{r}
# Dataset 2 (Movie)

mat_variance_weight_movie <- variance_weight_matrix(dim(movie_train)[1], mat = movie_train)
#mat_variance_weight_movie[is.na(mat_variance_weight_movie)] = 0
save(mat_variance_weight_movie, file = "variance_weight_Movie.RData")

# Dataset 1 (MS)

mat_variance_weight_MS <- variance_weight_matrix(dim(MS_train)[1], mat = MS_train)
#mat_variance_weight_MS[is.na(mat_variance_weight_MS)] = 0
save(mat_variance_weight_MS, file = "variance_weight_MS.RData")
```

